version: '3.8'

services:
  db:
    image: postgres:14.11
    container_name: abandb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: aban
      POSTGRES_USER: aban
      POSTGRES_PASSWORD: aban
    networks:
      - app-network

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aban
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - DATABASE_URL=postgres://aban:aban@db:5432/aban
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
